[theme]
base="dark"
primaryColor="#e76f51"          # Terracota / Tomate cálido
backgroundColor="#121212"       # Fondo oscuro elegante
secondaryBackgroundColor="#1e1e1e" # Contenedores y menús secundarios
textColor="#f4f4f9"             # Blanco marfil
font="sans serif"